theme: jekyll-theme-cayman
title: Ingrid2Python
description: Simple Ingrid to Python/Xarray Translations
logo: favicon.ico
markdown: CommonMarkGhPages
#markdown: kramdown
encoding: UTF-8

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
